npm install -g karma
npm install -g karma-cli
npm install -g karma-xml-reporter
npm install -g karma-chrome-launcher
npm install -g karma-jasmine
npm install -g karma-junit-reporter
npm install -g karma-ng-scenario
npm install -g karma-ng-html2js-preprocessor
npm install -g karma-coverage