// <auto-generated />
namespace AngularJSDemo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Initversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201406180206007_Init version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
